"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .appscopeconfigwithcustom import (
    AppscopeConfigWithCustom,
    AppscopeConfigWithCustomTypedDict,
)
from .cribllib import CriblLib
from cribl_sdk_python_fafo.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AppscopeLibEntryTypedDict(TypedDict):
    config: AppscopeConfigWithCustomTypedDict
    description: str
    id: str
    lib: CriblLib
    tags: NotRequired[str]


class AppscopeLibEntry(BaseModel):
    config: AppscopeConfigWithCustom

    description: str

    id: str

    lib: CriblLib

    tags: Optional[str] = None
