"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .savedquery import SavedQuery, SavedQueryTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CreateSavedQueryResponseTypedDict(TypedDict):
    r"""a list of SavedQuery objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[SavedQueryTypedDict]]


class CreateSavedQueryResponse(BaseModel):
    r"""a list of SavedQuery objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[SavedQuery]] = None
