"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .parserlibentry import ParserLibEntry, ParserLibEntryTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CreateParserResponseTypedDict(TypedDict):
    r"""a list of Parser objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[ParserLibEntryTypedDict]]


class CreateParserResponse(BaseModel):
    r"""a list of Parser objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[ParserLibEntry]] = None
