"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .captureparams import CaptureParams, CaptureParamsTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from cribl_sdk_python_fafo.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateSystemProjectsCaptureByGroupIDAndProjectIDRequestTypedDict(TypedDict):
    group_id: str
    r"""Group Id"""
    project_id: str
    r"""Project Id"""
    capture_params: CaptureParamsTypedDict
    r"""CaptureParams object"""


class CreateSystemProjectsCaptureByGroupIDAndProjectIDRequest(BaseModel):
    group_id: Annotated[
        str,
        pydantic.Field(alias="groupId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Group Id"""

    project_id: Annotated[
        str,
        pydantic.Field(alias="projectId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Project Id"""

    capture_params: Annotated[
        CaptureParams,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""CaptureParams object"""


class CreateSystemProjectsCaptureByGroupIDAndProjectIDResponseTypedDict(TypedDict):
    r"""A list of any objects"""

    count: NotRequired[int]
    r"""Number of items present in the items array"""
    items: NotRequired[List[Dict[str, Any]]]


class CreateSystemProjectsCaptureByGroupIDAndProjectIDResponse(BaseModel):
    r"""A list of any objects"""

    count: Optional[int] = None
    r"""Number of items present in the items array"""

    items: Optional[List[Dict[str, Any]]] = None
