"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_sdk_python_fafo.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DashboardCategoryTypedDict(TypedDict):
    id: str
    name: str
    description: NotRequired[str]
    is_pack: NotRequired[bool]


class DashboardCategory(BaseModel):
    id: str

    name: str

    description: Optional[str] = None

    is_pack: Annotated[Optional[bool], pydantic.Field(alias="isPack")] = None
