"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .symlinkinfo import SymLinkInfo, SymLinkInfoTypedDict
from cribl_sdk_python_fafo.types import BaseModel
import pydantic
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FilesystemEntryTypedDict(TypedDict):
    name: str
    type: str
    mode: NotRequired[str]
    stats: NotRequired[Dict[str, Any]]
    sym_link_info: NotRequired[SymLinkInfoTypedDict]


class FilesystemEntry(BaseModel):
    name: str

    type: str

    mode: Optional[str] = None

    stats: Optional[Dict[str, Any]] = None

    sym_link_info: Annotated[
        Optional[SymLinkInfo], pydantic.Field(alias="symLinkInfo")
    ] = None
