"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .changelogstate import ChangelogState, ChangelogStateTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GetChangelogViewedResponseTypedDict(TypedDict):
    r"""a list of ChangelogState objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[ChangelogStateTypedDict]]


class GetChangelogViewedResponse(BaseModel):
    r"""a list of ChangelogState objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[ChangelogState]] = None
