"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_sdk_python_fafo.types import BaseModel
from cribl_sdk_python_fafo.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetJobResultsByIDRequestTypedDict(TypedDict):
    id: str
    r"""Job instance id"""


class GetJobResultsByIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Job instance id"""
