"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .referencingentity import ReferencingEntity, ReferencingEntityTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from cribl_sdk_python_fafo.utils import FieldMetadata, PathParamMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetPacksRefsByIDRequestTypedDict(TypedDict):
    id: str
    r"""Pack name"""


class GetPacksRefsByIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Pack name"""


class GetPacksRefsByIDResponseTypedDict(TypedDict):
    r"""a list of ReferencingEntity objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[ReferencingEntityTypedDict]]


class GetPacksRefsByIDResponse(BaseModel):
    r"""a list of ReferencingEntity objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[ReferencingEntity]] = None
