"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .subscription import Subscription, SubscriptionTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from cribl_sdk_python_fafo.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetSubscriptionByProjectIDRequestTypedDict(TypedDict):
    project_id: str
    r"""Project Id"""


class GetSubscriptionByProjectIDRequest(BaseModel):
    project_id: Annotated[
        str,
        pydantic.Field(alias="projectId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Project Id"""


class GetSubscriptionByProjectIDResponseTypedDict(TypedDict):
    r"""a list of Subscription objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[SubscriptionTypedDict]]


class GetSubscriptionByProjectIDResponse(BaseModel):
    r"""a list of Subscription objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[Subscription]] = None
