"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_sdk_python_fafo.types import BaseModel
from cribl_sdk_python_fafo.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
import pydantic
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetSystemProjectsVersionDiffByProjectIDRequestTypedDict(TypedDict):
    project_id: str
    r"""Project Id"""
    commit: NotRequired[str]
    r"""Commit hash (default is HEAD)"""
    filename: NotRequired[str]
    r"""Filename"""
    diff_line_limit: NotRequired[float]
    r"""Limit maximum lines in the diff"""


class GetSystemProjectsVersionDiffByProjectIDRequest(BaseModel):
    project_id: Annotated[
        str,
        pydantic.Field(alias="projectId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Project Id"""

    commit: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Commit hash (default is HEAD)"""

    filename: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filename"""

    diff_line_limit: Annotated[
        Optional[float],
        pydantic.Field(alias="diffLineLimit"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Limit maximum lines in the diff"""


class GetSystemProjectsVersionDiffByProjectIDResponseTypedDict(TypedDict):
    r"""a list of any objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[Dict[str, Any]]]


class GetSystemProjectsVersionDiffByProjectIDResponse(BaseModel):
    r"""a list of any objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[Dict[str, Any]]] = None
