"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .subscription import Subscription, SubscriptionTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from cribl_sdk_python_fafo.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetSystemProjectsSubscriptionsByGroupIDByAndProjectIDRequestTypedDict(TypedDict):
    group_id: str
    r"""Group Id"""
    project_id: str
    r"""Project Id"""


class GetSystemProjectsSubscriptionsByGroupIDByAndProjectIDRequest(BaseModel):
    group_id: Annotated[
        str,
        pydantic.Field(alias="groupId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Group Id"""

    project_id: Annotated[
        str,
        pydantic.Field(alias="projectId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Project Id"""


class GetSystemProjectsSubscriptionsByGroupIDByAndProjectIDResponseTypedDict(TypedDict):
    r"""A list of Subscription objects"""

    count: NotRequired[int]
    r"""Number of items present in the items array"""
    items: NotRequired[List[SubscriptionTypedDict]]


class GetSystemProjectsSubscriptionsByGroupIDByAndProjectIDResponse(BaseModel):
    r"""A list of Subscription objects"""

    count: Optional[int] = None
    r"""Number of items present in the items array"""

    items: Optional[List[Subscription]] = None
