"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .searchsettings import SearchSettings, SearchSettingsTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GetSystemSettingsSearchLimitsResponseTypedDict(TypedDict):
    r"""a list of SearchSettings objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[SearchSettingsTypedDict]]


class GetSystemSettingsSearchLimitsResponse(BaseModel):
    r"""a list of SearchSettings objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[SearchSettings]] = None
