"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .user import User, UserTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from cribl_sdk_python_fafo.utils import FieldMetadata, PathParamMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetUserByIDRequestTypedDict(TypedDict):
    id: str
    r"""Unique ID to GET"""


class GetUserByIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique ID to GET"""


class GetUserByIDResponseTypedDict(TypedDict):
    r"""a list of User objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[UserTypedDict]]


class GetUserByIDResponse(BaseModel):
    r"""a list of User objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[User]] = None
