"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cribllib import CriblLib
from cribl_sdk_python_fafo.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class HmacFunctionTypedDict(TypedDict):
    header_expression: str
    header_name: str
    id: str
    lib: CriblLib
    string_builders: List[str]
    description: NotRequired[str]
    string_delim: NotRequired[str]


class HmacFunction(BaseModel):
    header_expression: Annotated[str, pydantic.Field(alias="headerExpression")]

    header_name: Annotated[str, pydantic.Field(alias="headerName")]

    id: str

    lib: CriblLib

    string_builders: Annotated[List[str], pydantic.Field(alias="stringBuilders")]

    description: Optional[str] = None

    string_delim: Annotated[Optional[str], pydantic.Field(alias="stringDelim")] = None
