"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_sdk_python_fafo.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class HTTPOutAuthConfigTypedDict(TypedDict):
    disabled: NotRequired[bool]
    password: NotRequired[str]
    token: NotRequired[str]
    username: NotRequired[str]


class HTTPOutAuthConfig(BaseModel):
    disabled: Optional[bool] = None

    password: Optional[str] = None

    token: Optional[str] = None

    username: Optional[str] = None
