"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_sdk_python_fafo.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class JobExecutionWarningTypedDict(TypedDict):
    type: str
    text: NotRequired[str]


class JobExecutionWarning(BaseModel):
    type: str

    text: Optional[str] = None
