"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .profileritem import ProfilerItem, ProfilerItemTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListProfilerItemResponseTypedDict(TypedDict):
    r"""a list of ProfilerItem objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[ProfilerItemTypedDict]]


class ListProfilerItemResponse(BaseModel):
    r"""a list of ProfilerItem objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[ProfilerItem]] = None
