"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_sdk_python_fafo.types import BaseModel
from typing_extensions import TypedDict


class LogFileInfoTypedDict(TypedDict):
    id: str
    path: str


class LogFileInfo(BaseModel):
    id: str

    path: str
