"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_sdk_python_fafo.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class LoggerEntryTypedDict(TypedDict):
    id: str
    level: str
    can_delete: NotRequired[bool]


class LoggerEntry(BaseModel):
    id: str

    level: str

    can_delete: Annotated[Optional[bool], pydantic.Field(alias="canDelete")] = None
