"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_sdk_python_fafo.types import BaseModel
from typing_extensions import TypedDict


class LookupFileInfoResponseTypedDict(TypedDict):
    filename: str
    rows: float
    size: float


class LookupFileInfoResponse(BaseModel):
    filename: str

    rows: float

    size: float
