"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .datasetorigin import DatasetOrigin
from cribl_sdk_python_fafo.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OriginConfigTypedDict(TypedDict):
    origin: DatasetOrigin
    filter_expression: NotRequired[str]


class OriginConfig(BaseModel):
    origin: DatasetOrigin

    filter_expression: Annotated[
        Optional[str], pydantic.Field(alias="filterExpression")
    ] = None
