"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .criblevent import CriblEvent, CriblEventTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class OutputTestRequestTypedDict(TypedDict):
    events: List[CriblEventTypedDict]


class OutputTestRequest(BaseModel):
    events: List[CriblEvent]
