"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chartconfig import ChartConfig, ChartConfigTypedDict
from .cribllib import CriblLib
from .savedqueryschedule import SavedQuerySchedule, SavedQueryScheduleTypedDict
from cribl_sdk_python_fafo.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SavedQueryTypedDict(TypedDict):
    id: str
    name: str
    query: str
    chart_config: NotRequired[ChartConfigTypedDict]
    description: NotRequired[str]
    display_username: NotRequired[str]
    earliest: NotRequired[str]
    is_private: NotRequired[bool]
    is_system: NotRequired[bool]
    latest: NotRequired[str]
    lib: NotRequired[CriblLib]
    resolved_dataset_ids: NotRequired[List[str]]
    sample_rate: NotRequired[float]
    schedule: NotRequired[SavedQueryScheduleTypedDict]
    table_config: NotRequired[str]
    user: NotRequired[str]


class SavedQuery(BaseModel):
    id: str

    name: str

    query: str

    chart_config: Annotated[
        Optional[ChartConfig], pydantic.Field(alias="chartConfig")
    ] = None

    description: Optional[str] = None

    display_username: Annotated[
        Optional[str], pydantic.Field(alias="displayUsername")
    ] = None

    earliest: Optional[str] = None

    is_private: Annotated[Optional[bool], pydantic.Field(alias="isPrivate")] = None

    is_system: Annotated[Optional[bool], pydantic.Field(alias="isSystem")] = None

    latest: Optional[str] = None

    lib: Optional[CriblLib] = None

    resolved_dataset_ids: Annotated[
        Optional[List[str]], pydantic.Field(alias="resolvedDatasetIds")
    ] = None

    sample_rate: Annotated[Optional[float], pydantic.Field(alias="sampleRate")] = None

    schedule: Optional[SavedQuerySchedule] = None

    table_config: Annotated[Optional[str], pydantic.Field(alias="tableConfig")] = None

    user: Optional[str] = None
