"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class SavesSearchRunMode(str, Enum):
    NEW_SEARCH = "newSearch"
    LAST_RUN = "lastRun"
