"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dashboardelement import DashboardElement, DashboardElementTypedDict
from .savedqueryschedule import SavedQuerySchedule, SavedQueryScheduleTypedDict
from cribl_sdk_python_fafo.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SearchDashboardTypedDict(TypedDict):
    created: float
    created_by: str
    elements: List[DashboardElementTypedDict]
    id: str
    modified: float
    name: str
    cache_ttl_seconds: NotRequired[float]
    category: NotRequired[str]
    description: NotRequired[str]
    display_created_by: NotRequired[str]
    display_modified_by: NotRequired[str]
    modified_by: NotRequired[str]
    pack_id: NotRequired[str]
    refresh_rate: NotRequired[float]
    resolved_dataset_ids: NotRequired[List[str]]
    schedule: NotRequired[SavedQueryScheduleTypedDict]


class SearchDashboard(BaseModel):
    created: float

    created_by: Annotated[str, pydantic.Field(alias="createdBy")]

    elements: List[DashboardElement]

    id: str

    modified: float

    name: str

    cache_ttl_seconds: Annotated[
        Optional[float], pydantic.Field(alias="cacheTTLSeconds")
    ] = None

    category: Optional[str] = None

    description: Optional[str] = None

    display_created_by: Annotated[
        Optional[str], pydantic.Field(alias="displayCreatedBy")
    ] = None

    display_modified_by: Annotated[
        Optional[str], pydantic.Field(alias="displayModifiedBy")
    ] = None

    modified_by: Annotated[Optional[str], pydantic.Field(alias="modifiedBy")] = None

    pack_id: Annotated[Optional[str], pydantic.Field(alias="packId")] = None

    refresh_rate: Annotated[Optional[float], pydantic.Field(alias="refreshRate")] = None

    resolved_dataset_ids: Annotated[
        Optional[List[str]], pydantic.Field(alias="resolvedDatasetIds")
    ] = None

    schedule: Optional[SavedQuerySchedule] = None
