"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_sdk_python_fafo.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class SearchTermTypedDict(TypedDict):
    is_case_sensitive: bool
    term: str


class SearchTerm(BaseModel):
    is_case_sensitive: Annotated[bool, pydantic.Field(alias="isCaseSensitive")]

    term: str
