"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .connection import Connection, ConnectionTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SubscriptionConsumerTypedDict(TypedDict):
    connections: NotRequired[List[ConnectionTypedDict]]
    disabled: NotRequired[bool]
    type: NotRequired[str]


class SubscriptionConsumer(BaseModel):
    connections: Optional[List[Connection]] = None

    disabled: Optional[bool] = None

    type: Optional[str] = None
