"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .usagegroup import UsageGroup, UsageGroupTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from cribl_sdk_python_fafo.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateUsageGroupByIDRequestTypedDict(TypedDict):
    id_param: str
    r"""Unique ID to PATCH"""
    usage_group: UsageGroupTypedDict
    r"""UsageGroup object to be updated"""


class UpdateUsageGroupByIDRequest(BaseModel):
    id_param: Annotated[
        str,
        pydantic.Field(alias="id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique ID to PATCH"""

    usage_group: Annotated[
        UsageGroup,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""UsageGroup object to be updated"""


class UpdateUsageGroupByIDResponseTypedDict(TypedDict):
    r"""a list of UsageGroup objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[UsageGroupTypedDict]]


class UpdateUsageGroupByIDResponse(BaseModel):
    r"""a list of UsageGroup objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[UsageGroup]] = None
