"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_sdk_python_fafo.types import BaseModel
from cribl_sdk_python_fafo.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from typing import Any, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateDatasetProviderByIDRequestTypedDict(TypedDict):
    id: str
    r"""Unique ID to PATCH"""
    request_body: Any
    r"""DatasetProvider object to be updated"""


class UpdateDatasetProviderByIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique ID to PATCH"""

    request_body: Annotated[
        Any, FieldMetadata(request=RequestMetadata(media_type="application/json"))
    ]
    r"""DatasetProvider object to be updated"""


class UpdateDatasetProviderByIDResponseTypedDict(TypedDict):
    r"""a list of DatasetProvider objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[Any]]


class UpdateDatasetProviderByIDResponse(BaseModel):
    r"""a list of DatasetProvider objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[Any]] = None
