"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .searchdashboard import SearchDashboard, SearchDashboardTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from cribl_sdk_python_fafo.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateSearchDashboardByIDRequestTypedDict(TypedDict):
    id_param: str
    r"""Unique ID to PATCH"""
    search_dashboard: SearchDashboardTypedDict
    r"""SearchDashboard object to be updated"""


class UpdateSearchDashboardByIDRequest(BaseModel):
    id_param: Annotated[
        str,
        pydantic.Field(alias="id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique ID to PATCH"""

    search_dashboard: Annotated[
        SearchDashboard,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""SearchDashboard object to be updated"""


class UpdateSearchDashboardByIDResponseTypedDict(TypedDict):
    r"""a list of SearchDashboard objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[SearchDashboardTypedDict]]


class UpdateSearchDashboardByIDResponse(BaseModel):
    r"""a list of SearchDashboard objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[SearchDashboard]] = None
