"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .searchjob import SearchJob, SearchJobTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from cribl_sdk_python_fafo.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateSearchJobByIDRequestTypedDict(TypedDict):
    id_param: str
    r"""Unique ID to PATCH"""
    search_job: SearchJobTypedDict
    r"""SearchJob object to be updated"""


class UpdateSearchJobByIDRequest(BaseModel):
    id_param: Annotated[
        str,
        pydantic.Field(alias="id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique ID to PATCH"""

    search_job: Annotated[
        SearchJob, FieldMetadata(request=RequestMetadata(media_type="application/json"))
    ]
    r"""SearchJob object to be updated"""


class UpdateSearchJobByIDResponseTypedDict(TypedDict):
    r"""a list of SearchJob objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[SearchJobTypedDict]]


class UpdateSearchJobByIDResponse(BaseModel):
    r"""a list of SearchJob objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[SearchJob]] = None
