"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .projectconfig import ProjectConfig, ProjectConfigTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from cribl_sdk_python_fafo.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateProjectByIDRequestTypedDict(TypedDict):
    id_param: str
    r"""Unique ID to PATCH"""
    project_config: ProjectConfigTypedDict
    r"""Project object to be updated"""


class UpdateProjectByIDRequest(BaseModel):
    id_param: Annotated[
        str,
        pydantic.Field(alias="id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique ID to PATCH"""

    project_config: Annotated[
        ProjectConfig,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Project object to be updated"""


class UpdateProjectByIDResponseTypedDict(TypedDict):
    r"""a list of Project objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[ProjectConfigTypedDict]]


class UpdateProjectByIDResponse(BaseModel):
    r"""a list of Project objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[ProjectConfig]] = None
