"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .schemalibentry import SchemaLibEntry, SchemaLibEntryTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from cribl_sdk_python_fafo.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateSchemaLibByPackAndIDRequestTypedDict(TypedDict):
    id_param: str
    r"""Unique ID to PATCH for pack"""
    pack: str
    r"""pack ID to PATCH"""
    schema_lib_entry: SchemaLibEntryTypedDict
    r"""Schema object to be updated"""


class UpdateSchemaLibByPackAndIDRequest(BaseModel):
    id_param: Annotated[
        str,
        pydantic.Field(alias="id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique ID to PATCH for pack"""

    pack: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""pack ID to PATCH"""

    schema_lib_entry: Annotated[
        SchemaLibEntry,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Schema object to be updated"""


class UpdateSchemaLibByPackAndIDResponseTypedDict(TypedDict):
    r"""a list of Schema objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[SchemaLibEntryTypedDict]]


class UpdateSchemaLibByPackAndIDResponse(BaseModel):
    r"""a list of Schema objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[SchemaLibEntry]] = None
