"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .resourcepolicy import ResourcePolicy, ResourcePolicyTypedDict
from cribl_sdk_python_fafo.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class UserAccessControlListTypedDict(TypedDict):
    perms: List[ResourcePolicyTypedDict]
    user: str


class UserAccessControlList(BaseModel):
    perms: List[ResourcePolicy]

    user: str
