// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PanelQueryDefinition struct {
	Alias   *string `json:"alias,omitempty"`
	LocalID string  `json:"localId"`
	Query   string  `json:"query"`
}

func (o *PanelQueryDefinition) GetAlias() *string {
	if o == nil {
		return nil
	}
	return o.Alias
}

func (o *PanelQueryDefinition) GetLocalID() string {
	if o == nil {
		return ""
	}
	return o.LocalID
}

func (o *PanelQueryDefinition) GetQuery() string {
	if o == nil {
		return ""
	}
	return o.Query
}
