workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Cribl API Reference:
        inputs:
            - location: ../openapi.yml
        registry:
            location: registry.speakeasyapi.dev/cribl/cribl/cribl-api-reference
targets:
    cribl:
        target: python
        source: Cribl API Reference
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/cribl/cribl/cribl-api-reference-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
