"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class BreakdownTypedDict(TypedDict):
    infrastructure_credits: float
    processing_credits: float
    search_credits: float
    lake_credits: float
    lakehouse_credits: float


class Breakdown(BaseModel):
    infrastructure_credits: Annotated[
        float, pydantic.Field(alias="infrastructureCredits")
    ]

    processing_credits: Annotated[float, pydantic.Field(alias="processingCredits")]

    search_credits: Annotated[float, pydantic.Field(alias="searchCredits")]

    lake_credits: Annotated[float, pydantic.Field(alias="lakeCredits")]

    lakehouse_credits: Annotated[float, pydantic.Field(alias="lakehouseCredits")]
