"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clickhousedescriptioncolumn import (
    ClickHouseDescriptionColumn,
    ClickHouseDescriptionColumnTypedDict,
)
from cribl.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ClickHouseDescriptionResultTypedDict(TypedDict):
    success: bool
    description: NotRequired[List[ClickHouseDescriptionColumnTypedDict]]
    error_msg: NotRequired[str]


class ClickHouseDescriptionResult(BaseModel):
    success: bool

    description: Optional[List[ClickHouseDescriptionColumn]] = None

    error_msg: Annotated[Optional[str], pydantic.Field(alias="errorMsg")] = None
