"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .commit import Commit, CommitTypedDict
from .configgroupcloud import ConfigGroupCloud, ConfigGroupCloudTypedDict
from cribl.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GitModelTypedDict(TypedDict):
    commit: NotRequired[str]
    local_changes: NotRequired[float]
    log: NotRequired[List[CommitTypedDict]]


class GitModel(BaseModel):
    commit: Optional[str] = None

    local_changes: Annotated[Optional[float], pydantic.Field(alias="localChanges")] = (
        None
    )

    log: Optional[List[Commit]] = None


class ConfigGroupTypedDict(TypedDict):
    config_version: str
    id: str
    cloud: NotRequired[ConfigGroupCloudTypedDict]
    deploying_worker_count: NotRequired[float]
    description: NotRequired[str]
    estimated_ingest_rate: NotRequired[float]
    git: NotRequired[GitModelTypedDict]
    incompatible_worker_count: NotRequired[float]
    inherits: NotRequired[str]
    is_fleet: NotRequired[bool]
    is_search: NotRequired[bool]
    name: NotRequired[str]
    on_prem: NotRequired[bool]
    provisioned: NotRequired[bool]
    streamtags: NotRequired[List[str]]
    tags: NotRequired[str]
    upgrade_version: NotRequired[str]
    worker_count: NotRequired[float]
    worker_remote_access: NotRequired[bool]


class ConfigGroup(BaseModel):
    config_version: Annotated[str, pydantic.Field(alias="configVersion")]

    id: str

    cloud: Optional[ConfigGroupCloud] = None

    deploying_worker_count: Annotated[
        Optional[float], pydantic.Field(alias="deployingWorkerCount")
    ] = None

    description: Optional[str] = None

    estimated_ingest_rate: Annotated[
        Optional[float], pydantic.Field(alias="estimatedIngestRate")
    ] = None

    git: Optional[GitModel] = None

    incompatible_worker_count: Annotated[
        Optional[float], pydantic.Field(alias="incompatibleWorkerCount")
    ] = None

    inherits: Optional[str] = None

    is_fleet: Annotated[Optional[bool], pydantic.Field(alias="isFleet")] = None

    is_search: Annotated[Optional[bool], pydantic.Field(alias="isSearch")] = None

    name: Optional[str] = None

    on_prem: Annotated[Optional[bool], pydantic.Field(alias="onPrem")] = None

    provisioned: Optional[bool] = None

    streamtags: Optional[List[str]] = None

    tags: Optional[str] = None

    upgrade_version: Annotated[
        Optional[str], pydantic.Field(alias="upgradeVersion")
    ] = None

    worker_count: Annotated[Optional[float], pydantic.Field(alias="workerCount")] = None

    worker_remote_access: Annotated[
        Optional[bool], pydantic.Field(alias="workerRemoteAccess")
    ] = None
