"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clickhousedescriptionresult import (
    ClickHouseDescriptionResult,
    ClickHouseDescriptionResultTypedDict,
)
from cribl.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CreateOutputClickHouseDescribeTableResponseBodyTypedDict(TypedDict):
    r"""a list of ClickHouseDescriptionResult objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[ClickHouseDescriptionResultTypedDict]]


class CreateOutputClickHouseDescribeTableResponseBody(BaseModel):
    r"""a list of ClickHouseDescriptionResult objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[ClickHouseDescriptionResult]] = None
