"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .eventbreakerruleset import EventBreakerRuleset, EventBreakerRulesetTypedDict
from cribl.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CreateEventBreakerRulesetResponseBodyTypedDict(TypedDict):
    r"""a list of Event Breaker Ruleset objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[EventBreakerRulesetTypedDict]]


class CreateEventBreakerRulesetResponseBody(BaseModel):
    r"""a list of Event Breaker Ruleset objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[EventBreakerRuleset]] = None
