"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .schemalibentry import SchemaLibEntry, SchemaLibEntryTypedDict
from cribl.types import BaseModel
from cribl.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateSchemaLibByPackRequestTypedDict(TypedDict):
    pack: str
    r"""pack ID to POST"""
    schema_lib_entry: SchemaLibEntryTypedDict
    r"""New Schema object"""


class CreateSchemaLibByPackRequest(BaseModel):
    pack: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""pack ID to POST"""

    schema_lib_entry: Annotated[
        SchemaLibEntry,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""New Schema object"""


class CreateSchemaLibByPackResponseBodyTypedDict(TypedDict):
    r"""a list of Schema objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[SchemaLibEntryTypedDict]]


class CreateSchemaLibByPackResponseBody(BaseModel):
    r"""a list of Schema objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[SchemaLibEntry]] = None
