"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .input import Input, InputTypedDict
from cribl.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CreateInputResponseBodyTypedDict(TypedDict):
    r"""a list of Input objects"""

    items: NotRequired[List[InputTypedDict]]


class CreateInputResponseBody(BaseModel):
    r"""a list of Input objects"""

    items: Optional[List[Input]] = None
