"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cacheconnection import CacheConnection, CacheConnectionTypedDict
from .lakedatasetsearchconfig import (
    LakeDatasetSearchConfig,
    LakeDatasetSearchConfigTypedDict,
)
from cribl.types import BaseModel
from enum import Enum
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CriblLakeDatasetFormat(str, Enum):
    JSON = "json"
    DDSS = "ddss"
    PARQUET = "parquet"


class CriblLakeDatasetTypedDict(TypedDict):
    bucket_name: str
    id: str
    accelerated_fields: NotRequired[List[str]]
    cache_connection: NotRequired[CacheConnectionTypedDict]
    deletion_started_at: NotRequired[float]
    description: NotRequired[str]
    format_: NotRequired[CriblLakeDatasetFormat]
    retention_period_in_days: NotRequired[float]
    search_config: NotRequired[LakeDatasetSearchConfigTypedDict]
    view_name: NotRequired[str]


class CriblLakeDataset(BaseModel):
    bucket_name: Annotated[str, pydantic.Field(alias="bucketName")]

    id: str

    accelerated_fields: Annotated[
        Optional[List[str]], pydantic.Field(alias="acceleratedFields")
    ] = None

    cache_connection: Annotated[
        Optional[CacheConnection], pydantic.Field(alias="cacheConnection")
    ] = None

    deletion_started_at: Annotated[
        Optional[float], pydantic.Field(alias="deletionStartedAt")
    ] = None

    description: Optional[str] = None

    format_: Annotated[
        Optional[CriblLakeDatasetFormat], pydantic.Field(alias="format")
    ] = None

    retention_period_in_days: Annotated[
        Optional[float], pydantic.Field(alias="retentionPeriodInDays")
    ] = None

    search_config: Annotated[
        Optional[LakeDatasetSearchConfig], pydantic.Field(alias="searchConfig")
    ] = None

    view_name: Annotated[Optional[str], pydantic.Field(alias="viewName")] = None
