"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .notificationtarget import NotificationTarget, NotificationTargetTypedDict
from cribl.types import BaseModel
from cribl.utils import FieldMetadata, PathParamMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeleteNotificationTargetByIDRequestTypedDict(TypedDict):
    id: str
    r"""Unique ID to DELETE"""


class DeleteNotificationTargetByIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique ID to DELETE"""


class DeleteNotificationTargetByIDResponseBodyTypedDict(TypedDict):
    r"""a list of NotificationTarget objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[NotificationTargetTypedDict]]


class DeleteNotificationTargetByIDResponseBody(BaseModel):
    r"""a list of NotificationTarget objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[NotificationTarget]] = None
