"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .searchmacro import SearchMacro, SearchMacroTypedDict
from cribl.types import BaseModel
from cribl.utils import FieldMetadata, PathParamMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeleteSearchMacroByIDRequestTypedDict(TypedDict):
    id: str
    r"""Unique ID to DELETE"""


class DeleteSearchMacroByIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique ID to DELETE"""


class DeleteSearchMacroByIDResponseBodyTypedDict(TypedDict):
    r"""a list of SearchMacro objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[SearchMacroTypedDict]]


class DeleteSearchMacroByIDResponseBody(BaseModel):
    r"""a list of SearchMacro objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[SearchMacro]] = None
