"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .policyrule import PolicyRule, PolicyRuleTypedDict
from cribl.types import BaseModel
from cribl.utils import FieldMetadata, PathParamMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeletePolicyRuleByIDRequestTypedDict(TypedDict):
    id: str
    r"""Unique ID to DELETE"""


class DeletePolicyRuleByIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique ID to DELETE"""


class DeletePolicyRuleByIDResponseBodyTypedDict(TypedDict):
    r"""a list of PolicyRule objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[PolicyRuleTypedDict]]


class DeletePolicyRuleByIDResponseBody(BaseModel):
    r"""a list of PolicyRule objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[PolicyRule]] = None
