"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dockergraphdriverdata import DockerGraphDriverData, DockerGraphDriverDataTypedDict
from cribl.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DockerGraphDriverTypedDict(TypedDict):
    data: NotRequired[DockerGraphDriverDataTypedDict]


class DockerGraphDriver(BaseModel):
    data: Annotated[Optional[DockerGraphDriverData], pydantic.Field(alias="Data")] = (
        None
    )
