"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .breakdown import Breakdown, BreakdownTypedDict
from cribl.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetCreditsDTOTypedDict(TypedDict):
    total_credits_purchased: float
    total_credits_used: float
    total_credits_available: float
    breakdown: NotRequired[BreakdownTypedDict]


class GetCreditsDTO(BaseModel):
    total_credits_purchased: Annotated[
        float, pydantic.Field(alias="totalCreditsPurchased")
    ]

    total_credits_used: Annotated[float, pydantic.Field(alias="totalCreditsUsed")]

    total_credits_available: Annotated[
        float, pydantic.Field(alias="totalCreditsAvailable")
    ]

    breakdown: Optional[Breakdown] = None
