"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl.types import BaseModel
from cribl.utils import FieldMetadata, PathParamMetadata
from typing import Any, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetDatasetByIDRequestTypedDict(TypedDict):
    id: str
    r"""Unique ID to GET"""


class GetDatasetByIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique ID to GET"""


class GetDatasetByIDResponseBodyTypedDict(TypedDict):
    r"""a list of Dataset objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[Any]]


class GetDatasetByIDResponseBody(BaseModel):
    r"""a list of Dataset objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[Any]] = None
