"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .container import Container, ContainerTypedDict
from cribl.types import BaseModel
from cribl.utils import FieldMetadata, PathParamMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetEdgeContainersByIDRequestTypedDict(TypedDict):
    id: str
    r"""ID"""


class GetEdgeContainersByIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""ID"""


class GetEdgeContainersByIDResponseBodyTypedDict(TypedDict):
    r"""a list of Container objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[ContainerTypedDict]]


class GetEdgeContainersByIDResponseBody(BaseModel):
    r"""a list of Container objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[Container]] = None
