"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl.types import BaseModel
from cribl.utils import FieldMetadata, PathParamMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetGroupsConfigVersionByIDRequestTypedDict(TypedDict):
    id: str
    r"""Group ID"""


class GetGroupsConfigVersionByIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Group ID"""


class GetGroupsConfigVersionByIDResponseBodyTypedDict(TypedDict):
    r"""a list of string objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[str]]


class GetGroupsConfigVersionByIDResponseBody(BaseModel):
    r"""a list of string objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[str]] = None
