"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .keymetadataentity import KeyMetadataEntity, KeyMetadataEntityTypedDict
from cribl.types import BaseModel
from cribl.utils import FieldMetadata, PathParamMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetKeyMetadataEntityByIDRequestTypedDict(TypedDict):
    id: str
    r"""Unique ID to GET"""


class GetKeyMetadataEntityByIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique ID to GET"""


class GetKeyMetadataEntityByIDResponseBodyTypedDict(TypedDict):
    r"""a list of KeyMetadataEntity objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[KeyMetadataEntityTypedDict]]


class GetKeyMetadataEntityByIDResponseBody(BaseModel):
    r"""a list of KeyMetadataEntity objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[KeyMetadataEntity]] = None
