"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .license import License, LicenseTypedDict
from cribl.types import BaseModel
from cribl.utils import FieldMetadata, PathParamMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetLicenseByIDRequestTypedDict(TypedDict):
    id: str
    r"""Unique ID to GET"""


class GetLicenseByIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique ID to GET"""


class GetLicenseByIDResponseBodyTypedDict(TypedDict):
    r"""a list of License objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[LicenseTypedDict]]


class GetLicenseByIDResponseBody(BaseModel):
    r"""a list of License objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[License]] = None
