"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl.types import BaseModel
from cribl.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class GetSearchJobsStagesResultsByIDAndStageIDRequestTypedDict(TypedDict):
    id: str
    r"""search job ID"""
    stage_id: str
    r"""id of the search job stage"""


class GetSearchJobsStagesResultsByIDAndStageIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""search job ID"""

    stage_id: Annotated[
        str,
        pydantic.Field(alias="stageId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""id of the search job stage"""
