"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .kmsproviderconfig import KMSProviderConfig, KMSProviderConfigTypedDict
from cribl.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GetSecurityKmsConfigResponseBodyTypedDict(TypedDict):
    r"""a list of KMSProviderConfig objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[KMSProviderConfigTypedDict]]


class GetSecurityKmsConfigResponseBody(BaseModel):
    r"""a list of KMSProviderConfig objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[KMSProviderConfig]] = None
