"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl.types import BaseModel
from cribl.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetSearchJobsMetricsByIDRequestTypedDict(TypedDict):
    id: str
    r"""search job id"""


class GetSearchJobsMetricsByIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""search job id"""
