"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .routes_input import Routes, RoutesTypedDict
from cribl.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListRoutesResponseBodyTypedDict(TypedDict):
    r"""a list of Routes objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[RoutesTypedDict]]


class ListRoutesResponseBody(BaseModel):
    r"""a list of Routes objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[Routes]] = None
