"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .function import Function, FunctionTypedDict
from cribl.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListFunctionResponseBodyTypedDict(TypedDict):
    r"""a list of Function objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[FunctionTypedDict]]


class ListFunctionResponseBody(BaseModel):
    r"""a list of Function objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[Function]] = None
