"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .productslugv5 import ProductSlugV5
from .productunitstatsv5 import ProductUnitStatsV5, ProductUnitStatsV5TypedDict
from cribl.types import BaseModel
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class SingleProductConsumptionStatsV5TypedDict(TypedDict):
    slug: ProductSlugV5
    total_credits: float
    per_unit: List[ProductUnitStatsV5TypedDict]


class SingleProductConsumptionStatsV5(BaseModel):
    slug: ProductSlugV5

    total_credits: Annotated[float, pydantic.Field(alias="totalCredits")]

    per_unit: Annotated[List[ProductUnitStatsV5], pydantic.Field(alias="perUnit")]
