"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl.types import BaseModel
from cribl.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


V5_BILLING_INVOICES_GET_INVOICE_OP_SERVERS = [
    "https://api.cribl-staging.cloud",
]


class V5BillingInvoicesGetInvoiceRequestTypedDict(TypedDict):
    organization_id: str
    invoice_id: str


class V5BillingInvoicesGetInvoiceRequest(BaseModel):
    organization_id: Annotated[
        str,
        pydantic.Field(alias="organizationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    invoice_id: Annotated[
        str,
        pydantic.Field(alias="invoiceId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
