"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class VersionInfoTypedDict(TypedDict):
    build: str
    full_version: str
    major: float
    minor: float
    architecture: NotRequired[str]
    download_url: NotRequired[str]
    platform: NotRequired[str]
    point: NotRequired[float]
    pre_release: NotRequired[str]


class VersionInfo(BaseModel):
    build: str

    full_version: Annotated[str, pydantic.Field(alias="fullVersion")]

    major: float

    minor: float

    architecture: Optional[str] = None

    download_url: Annotated[Optional[str], pydantic.Field(alias="downloadUrl")] = None

    platform: Optional[str] = None

    point: Optional[float] = None

    pre_release: Annotated[Optional[str], pydantic.Field(alias="preRelease")] = None
