"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .workspacedto import WorkspaceDTO, WorkspaceDTOTypedDict
from cribl.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class WorkspacesDTOTypedDict(TypedDict):
    items: List[WorkspaceDTOTypedDict]
    count: float


class WorkspacesDTO(BaseModel):
    items: List[WorkspaceDTO]

    count: float
