// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// CreateSchemaResponseBody - a list of Schema objects
type CreateSchemaResponseBody struct {
	// number of items present in the items array
	Count *int64                      `json:"count,omitempty"`
	Items []components.SchemaLibEntry `json:"items,omitempty"`
}

func (o *CreateSchemaResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateSchemaResponseBody) GetItems() []components.SchemaLibEntry {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateSchemaResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Schema objects
	Object *CreateSchemaResponseBody
}

func (o *CreateSchemaResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateSchemaResponse) GetObject() *CreateSchemaResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
