// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateEdgeAppscopeProcessesRequest struct {
	// config string required
	Pid string `queryParam:"style=form,explode=true,name=pid"`
}

func (o *CreateEdgeAppscopeProcessesRequest) GetPid() string {
	if o == nil {
		return ""
	}
	return o.Pid
}

// CreateEdgeAppscopeProcessesResponseBody - a list of AppScopeProcess objects
type CreateEdgeAppscopeProcessesResponseBody struct {
	// number of items present in the items array
	Count *int64                       `json:"count,omitempty"`
	Items []components.AppScopeProcess `json:"items,omitempty"`
}

func (o *CreateEdgeAppscopeProcessesResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateEdgeAppscopeProcessesResponseBody) GetItems() []components.AppScopeProcess {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateEdgeAppscopeProcessesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of AppScopeProcess objects
	Object *CreateEdgeAppscopeProcessesResponseBody
}

func (o *CreateEdgeAppscopeProcessesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateEdgeAppscopeProcessesResponse) GetObject() *CreateEdgeAppscopeProcessesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
