// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// CreateSavedJobResponseBody - a list of SavedJob objects
type CreateSavedJobResponseBody struct {
	// number of items present in the items array
	Count *int64                `json:"count,omitempty"`
	Items []components.SavedJob `json:"items,omitempty"`
}

func (o *CreateSavedJobResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateSavedJobResponseBody) GetItems() []components.SavedJob {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateSavedJobResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of SavedJob objects
	Object *CreateSavedJobResponseBody
}

func (o *CreateSavedJobResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateSavedJobResponse) GetObject() *CreateSavedJobResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
