// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// CreateTeamResponseBody - a list of Team objects
type CreateTeamResponseBody struct {
	// number of items present in the items array
	Count *int64            `json:"count,omitempty"`
	Items []components.Team `json:"items,omitempty"`
}

func (o *CreateTeamResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateTeamResponseBody) GetItems() []components.Team {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateTeamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Team objects
	Object *CreateTeamResponseBody
}

func (o *CreateTeamResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateTeamResponse) GetObject() *CreateTeamResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
