// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// CreateOutputClickHouseDescribeTableResponseBody - a list of ClickHouseDescriptionResult objects
type CreateOutputClickHouseDescribeTableResponseBody struct {
	// number of items present in the items array
	Count *int64                                   `json:"count,omitempty"`
	Items []components.ClickHouseDescriptionResult `json:"items,omitempty"`
}

func (o *CreateOutputClickHouseDescribeTableResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateOutputClickHouseDescribeTableResponseBody) GetItems() []components.ClickHouseDescriptionResult {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateOutputClickHouseDescribeTableResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of ClickHouseDescriptionResult objects
	Object *CreateOutputClickHouseDescribeTableResponseBody
}

func (o *CreateOutputClickHouseDescribeTableResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateOutputClickHouseDescribeTableResponse) GetObject() *CreateOutputClickHouseDescribeTableResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
