// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// CreateSearchDashboardResponseBody - a list of SearchDashboard objects
type CreateSearchDashboardResponseBody struct {
	// number of items present in the items array
	Count *int64                       `json:"count,omitempty"`
	Items []components.SearchDashboard `json:"items,omitempty"`
}

func (o *CreateSearchDashboardResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateSearchDashboardResponseBody) GetItems() []components.SearchDashboard {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateSearchDashboardResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of SearchDashboard objects
	Object *CreateSearchDashboardResponseBody
}

func (o *CreateSearchDashboardResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateSearchDashboardResponse) GetObject() *CreateSearchDashboardResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
