// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateDatasetACLApplyByIDRequest struct {
	// Unique ID for ACL Create
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// AccessControlSchema object
	AccessControlSchema components.AccessControlSchema `request:"mediaType=application/json"`
}

func (o *CreateDatasetACLApplyByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateDatasetACLApplyByIDRequest) GetAccessControlSchema() components.AccessControlSchema {
	if o == nil {
		return components.AccessControlSchema{}
	}
	return o.AccessControlSchema
}

type CreateDatasetACLApplyByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *CreateDatasetACLApplyByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
