// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateSystemProjectsVersionCommitByGroupIDAndProjectIDRequest struct {
	// Group Id
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
	// Project Id
	ProjectID string `pathParam:"style=simple,explode=false,name=projectId"`
	// ProjectGitCommitParams object
	ProjectGitCommitParams components.ProjectGitCommitParams `request:"mediaType=application/json"`
}

func (o *CreateSystemProjectsVersionCommitByGroupIDAndProjectIDRequest) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

func (o *CreateSystemProjectsVersionCommitByGroupIDAndProjectIDRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *CreateSystemProjectsVersionCommitByGroupIDAndProjectIDRequest) GetProjectGitCommitParams() components.ProjectGitCommitParams {
	if o == nil {
		return components.ProjectGitCommitParams{}
	}
	return o.ProjectGitCommitParams
}

// CreateSystemProjectsVersionCommitByGroupIDAndProjectIDResponseBody - A list of GitCommitSummary objects
type CreateSystemProjectsVersionCommitByGroupIDAndProjectIDResponseBody struct {
	// Number of items present in the items array
	Count *int64                        `json:"count,omitempty"`
	Items []components.GitCommitSummary `json:"items,omitempty"`
}

func (o *CreateSystemProjectsVersionCommitByGroupIDAndProjectIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateSystemProjectsVersionCommitByGroupIDAndProjectIDResponseBody) GetItems() []components.GitCommitSummary {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateSystemProjectsVersionCommitByGroupIDAndProjectIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of GitCommitSummary objects
	Object *CreateSystemProjectsVersionCommitByGroupIDAndProjectIDResponseBody
}

func (o *CreateSystemProjectsVersionCommitByGroupIDAndProjectIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateSystemProjectsVersionCommitByGroupIDAndProjectIDResponse) GetObject() *CreateSystemProjectsVersionCommitByGroupIDAndProjectIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
