// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// CreateSavedQueryResponseBody - a list of SavedQuery objects
type CreateSavedQueryResponseBody struct {
	// number of items present in the items array
	Count *int64                  `json:"count,omitempty"`
	Items []components.SavedQuery `json:"items,omitempty"`
}

func (o *CreateSavedQueryResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateSavedQueryResponseBody) GetItems() []components.SavedQuery {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateSavedQueryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of SavedQuery objects
	Object *CreateSavedQueryResponseBody
}

func (o *CreateSavedQueryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateSavedQueryResponse) GetObject() *CreateSavedQueryResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
