// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// CreateEventBreakerRulesetResponseBody - a list of Event Breaker Ruleset objects
type CreateEventBreakerRulesetResponseBody struct {
	// number of items present in the items array
	Count *int64                           `json:"count,omitempty"`
	Items []components.EventBreakerRuleset `json:"items,omitempty"`
}

func (o *CreateEventBreakerRulesetResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateEventBreakerRulesetResponseBody) GetItems() []components.EventBreakerRuleset {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateEventBreakerRulesetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Event Breaker Ruleset objects
	Object *CreateEventBreakerRulesetResponseBody
}

func (o *CreateEventBreakerRulesetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateEventBreakerRulesetResponse) GetObject() *CreateEventBreakerRulesetResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
