// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteNotificationByIDRequest struct {
	// Unique ID to DELETE
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteNotificationByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// DeleteNotificationByIDResponseBody - a list of Notification objects
type DeleteNotificationByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                    `json:"count,omitempty"`
	Items []components.Notification `json:"items,omitempty"`
}

func (o *DeleteNotificationByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *DeleteNotificationByIDResponseBody) GetItems() []components.Notification {
	if o == nil {
		return nil
	}
	return o.Items
}

type DeleteNotificationByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Notification objects
	Object *DeleteNotificationByIDResponseBody
}

func (o *DeleteNotificationByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteNotificationByIDResponse) GetObject() *DeleteNotificationByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
