// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteSavedQueryByIDRequest struct {
	// Unique ID to DELETE
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteSavedQueryByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// DeleteSavedQueryByIDResponseBody - a list of SavedQuery objects
type DeleteSavedQueryByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                  `json:"count,omitempty"`
	Items []components.SavedQuery `json:"items,omitempty"`
}

func (o *DeleteSavedQueryByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *DeleteSavedQueryByIDResponseBody) GetItems() []components.SavedQuery {
	if o == nil {
		return nil
	}
	return o.Items
}

type DeleteSavedQueryByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of SavedQuery objects
	Object *DeleteSavedQueryByIDResponseBody
}

func (o *DeleteSavedQueryByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteSavedQueryByIDResponse) GetObject() *DeleteSavedQueryByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
