// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeletePolicyRuleByIDRequest struct {
	// Unique ID to DELETE
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeletePolicyRuleByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// DeletePolicyRuleByIDResponseBody - a list of PolicyRule objects
type DeletePolicyRuleByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                  `json:"count,omitempty"`
	Items []components.PolicyRule `json:"items,omitempty"`
}

func (o *DeletePolicyRuleByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *DeletePolicyRuleByIDResponseBody) GetItems() []components.PolicyRule {
	if o == nil {
		return nil
	}
	return o.Items
}

type DeletePolicyRuleByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of PolicyRule objects
	Object *DeletePolicyRuleByIDResponseBody
}

func (o *DeletePolicyRuleByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeletePolicyRuleByIDResponse) GetObject() *DeletePolicyRuleByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
