// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteDatasetProviderTypeByIDRequest struct {
	// Unique ID to DELETE
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteDatasetProviderTypeByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// DeleteDatasetProviderTypeByIDResponseBody - a list of DatasetProviderType objects
type DeleteDatasetProviderTypeByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                           `json:"count,omitempty"`
	Items []components.DatasetProviderType `json:"items,omitempty"`
}

func (o *DeleteDatasetProviderTypeByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *DeleteDatasetProviderTypeByIDResponseBody) GetItems() []components.DatasetProviderType {
	if o == nil {
		return nil
	}
	return o.Items
}

type DeleteDatasetProviderTypeByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of DatasetProviderType objects
	Object *DeleteDatasetProviderTypeByIDResponseBody
}

func (o *DeleteDatasetProviderTypeByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteDatasetProviderTypeByIDResponse) GetObject() *DeleteDatasetProviderTypeByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
