// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteAuthUsersTokenByIDRequest struct {
	// ID of user to invalidate
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// TTL of the token being invalidated
	TTL *string `queryParam:"style=form,explode=true,name=ttl"`
}

func (o *DeleteAuthUsersTokenByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DeleteAuthUsersTokenByIDRequest) GetTTL() *string {
	if o == nil {
		return nil
	}
	return o.TTL
}

// DeleteAuthUsersTokenByIDResponseBody - a list of any objects
type DeleteAuthUsersTokenByIDResponseBody struct {
	// number of items present in the items array
	Count *int64           `json:"count,omitempty"`
	Items []map[string]any `json:"items,omitempty"`
}

func (o *DeleteAuthUsersTokenByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *DeleteAuthUsersTokenByIDResponseBody) GetItems() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Items
}

type DeleteAuthUsersTokenByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of any objects
	Object *DeleteAuthUsersTokenByIDResponseBody
}

func (o *DeleteAuthUsersTokenByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteAuthUsersTokenByIDResponse) GetObject() *DeleteAuthUsersTokenByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
