// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetAuthSsoCallbackRequest struct {
	// Authentication request object
	SAMLResponse *string `queryParam:"style=form,explode=true,name=SAMLResponse"`
	RelayState   *string `queryParam:"style=form,explode=true,name=RelayState"`
}

func (o *GetAuthSsoCallbackRequest) GetSAMLResponse() *string {
	if o == nil {
		return nil
	}
	return o.SAMLResponse
}

func (o *GetAuthSsoCallbackRequest) GetRelayState() *string {
	if o == nil {
		return nil
	}
	return o.RelayState
}

type GetAuthSsoCallbackResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *GetAuthSsoCallbackResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
