// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetDatasetProviderTypeByIDRequest struct {
	// Unique ID to GET
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetDatasetProviderTypeByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetDatasetProviderTypeByIDResponseBody - a list of DatasetProviderType objects
type GetDatasetProviderTypeByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                           `json:"count,omitempty"`
	Items []components.DatasetProviderType `json:"items,omitempty"`
}

func (o *GetDatasetProviderTypeByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetDatasetProviderTypeByIDResponseBody) GetItems() []components.DatasetProviderType {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetDatasetProviderTypeByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of DatasetProviderType objects
	Object *GetDatasetProviderTypeByIDResponseBody
}

func (o *GetDatasetProviderTypeByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetDatasetProviderTypeByIDResponse) GetObject() *GetDatasetProviderTypeByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
