// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// GetEdgeProcessesResponseBody - a list of Process objects
type GetEdgeProcessesResponseBody struct {
	// number of items present in the items array
	Count *int64               `json:"count,omitempty"`
	Items []components.Process `json:"items,omitempty"`
}

func (o *GetEdgeProcessesResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetEdgeProcessesResponseBody) GetItems() []components.Process {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetEdgeProcessesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Process objects
	Object *GetEdgeProcessesResponseBody
}

func (o *GetEdgeProcessesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetEdgeProcessesResponse) GetObject() *GetEdgeProcessesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
