// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetEdgeFileSampleRequest struct {
	// The path to the file to sample
	Path string `queryParam:"style=form,explode=true,name=path"`
	// The number of bytes to return;   this value could be constrained by system limits.
	BytesRequested *float64 `queryParam:"style=form,explode=true,name=bytesRequested"`
}

func (o *GetEdgeFileSampleRequest) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}

func (o *GetEdgeFileSampleRequest) GetBytesRequested() *float64 {
	if o == nil {
		return nil
	}
	return o.BytesRequested
}

// GetEdgeFileSampleResponseBody - a list of SampleFile objects
type GetEdgeFileSampleResponseBody struct {
	// number of items present in the items array
	Count *int64                  `json:"count,omitempty"`
	Items []components.SampleFile `json:"items,omitempty"`
}

func (o *GetEdgeFileSampleResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetEdgeFileSampleResponseBody) GetItems() []components.SampleFile {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetEdgeFileSampleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of SampleFile objects
	Object *GetEdgeFileSampleResponseBody
}

func (o *GetEdgeFileSampleResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetEdgeFileSampleResponse) GetObject() *GetEdgeFileSampleResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
