// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetEventBreakerRulesetByIDRequest struct {
	// Unique ID to GET
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetEventBreakerRulesetByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetEventBreakerRulesetByIDResponseBody - a list of Event Breaker Ruleset objects
type GetEventBreakerRulesetByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                           `json:"count,omitempty"`
	Items []components.EventBreakerRuleset `json:"items,omitempty"`
}

func (o *GetEventBreakerRulesetByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetEventBreakerRulesetByIDResponseBody) GetItems() []components.EventBreakerRuleset {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetEventBreakerRulesetByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Event Breaker Ruleset objects
	Object *GetEventBreakerRulesetByIDResponseBody
}

func (o *GetEventBreakerRulesetByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetEventBreakerRulesetByIDResponse) GetObject() *GetEventBreakerRulesetByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
