// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// GetFeaturesEntryResponseBody - a list of FeaturesEntry objects
type GetFeaturesEntryResponseBody struct {
	// number of items present in the items array
	Count *int64                     `json:"count,omitempty"`
	Items []components.FeaturesEntry `json:"items,omitempty"`
}

func (o *GetFeaturesEntryResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetFeaturesEntryResponseBody) GetItems() []components.FeaturesEntry {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetFeaturesEntryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of FeaturesEntry objects
	Object *GetFeaturesEntryResponseBody
}

func (o *GetFeaturesEntryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetFeaturesEntryResponse) GetObject() *GetFeaturesEntryResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
