// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetGrokFileByIDRequest struct {
	// Unique ID to GET
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetGrokFileByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetGrokFileByIDResponseBody - a list of GrokFile objects
type GetGrokFileByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                `json:"count,omitempty"`
	Items []components.GrokFile `json:"items,omitempty"`
}

func (o *GetGrokFileByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetGrokFileByIDResponseBody) GetItems() []components.GrokFile {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetGrokFileByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of GrokFile objects
	Object *GetGrokFileByIDResponseBody
}

func (o *GetGrokFileByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetGrokFileByIDResponse) GetObject() *GetGrokFileByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
