// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetGlobalVariableByIDRequest struct {
	// Unique ID to GET
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetGlobalVariableByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetGlobalVariableByIDResponseBody - a list of Global Variable objects
type GetGlobalVariableByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                 `json:"count,omitempty"`
	Items []components.GlobalVar `json:"items,omitempty"`
}

func (o *GetGlobalVariableByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetGlobalVariableByIDResponseBody) GetItems() []components.GlobalVar {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetGlobalVariableByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Global Variable objects
	Object *GetGlobalVariableByIDResponseBody
}

func (o *GetGlobalVariableByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetGlobalVariableByIDResponse) GetObject() *GetGlobalVariableByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
