// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetLoggerConfigByIDRequest struct {
	// Unique ID to GET
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetLoggerConfigByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetLoggerConfigByIDResponseBody - a list of LoggerConfig objects
type GetLoggerConfigByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                    `json:"count,omitempty"`
	Items []components.LoggerConfig `json:"items,omitempty"`
}

func (o *GetLoggerConfigByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetLoggerConfigByIDResponseBody) GetItems() []components.LoggerConfig {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetLoggerConfigByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of LoggerConfig objects
	Object *GetLoggerConfigByIDResponseBody
}

func (o *GetLoggerConfigByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetLoggerConfigByIDResponse) GetObject() *GetLoggerConfigByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
