// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetRoleByIDRequest struct {
	// Unique ID to GET
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetRoleByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetRoleByIDResponseBody - a list of Role objects
type GetRoleByIDResponseBody struct {
	// number of items present in the items array
	Count *int64            `json:"count,omitempty"`
	Items []components.Role `json:"items,omitempty"`
}

func (o *GetRoleByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetRoleByIDResponseBody) GetItems() []components.Role {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetRoleByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Role objects
	Object *GetRoleByIDResponseBody
}

func (o *GetRoleByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetRoleByIDResponse) GetObject() *GetRoleByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
