// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// GetSearchHealthcheckResponseBody - a list of SearchHealthCheckStatus objects
type GetSearchHealthcheckResponseBody struct {
	// number of items present in the items array
	Count *int64                               `json:"count,omitempty"`
	Items []components.SearchHealthCheckStatus `json:"items,omitempty"`
}

func (o *GetSearchHealthcheckResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetSearchHealthcheckResponseBody) GetItems() []components.SearchHealthCheckStatus {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetSearchHealthcheckResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of SearchHealthCheckStatus objects
	Object *GetSearchHealthcheckResponseBody
}

func (o *GetSearchHealthcheckResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSearchHealthcheckResponse) GetObject() *GetSearchHealthcheckResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
