// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetSchemaLibByPackRequest struct {
	// pack ID to GET
	Pack string `pathParam:"style=simple,explode=false,name=pack"`
}

func (o *GetSchemaLibByPackRequest) GetPack() string {
	if o == nil {
		return ""
	}
	return o.Pack
}

// GetSchemaLibByPackResponseBody - a list of Schema objects
type GetSchemaLibByPackResponseBody struct {
	// number of items present in the items array
	Count *int64                      `json:"count,omitempty"`
	Items []components.SchemaLibEntry `json:"items,omitempty"`
}

func (o *GetSchemaLibByPackResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetSchemaLibByPackResponseBody) GetItems() []components.SchemaLibEntry {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetSchemaLibByPackResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Schema objects
	Object *GetSchemaLibByPackResponseBody
}

func (o *GetSchemaLibByPackResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSchemaLibByPackResponse) GetObject() *GetSchemaLibByPackResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
