// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetSearchJobSettingsByIDRequest struct {
	// search job id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetSearchJobSettingsByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetSearchJobSettingsByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// SearchJobSettings object
	SearchJobSettings *components.SearchJobSettings
}

func (o *GetSearchJobSettingsByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSearchJobSettingsByIDResponse) GetSearchJobSettings() *components.SearchJobSettings {
	if o == nil {
		return nil
	}
	return o.SearchJobSettings
}
