// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetSavedQueryByIDRequest struct {
	// Unique ID to GET
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetSavedQueryByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetSavedQueryByIDResponseBody - a list of SavedQuery objects
type GetSavedQueryByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                  `json:"count,omitempty"`
	Items []components.SavedQuery `json:"items,omitempty"`
}

func (o *GetSavedQueryByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetSavedQueryByIDResponseBody) GetItems() []components.SavedQuery {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetSavedQueryByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of SavedQuery objects
	Object *GetSavedQueryByIDResponseBody
}

func (o *GetSavedQueryByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSavedQueryByIDResponse) GetObject() *GetSavedQueryByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
