// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// GetSystemSettingsSearchLimitsResponseBody - a list of SearchSettings objects
type GetSystemSettingsSearchLimitsResponseBody struct {
	// number of items present in the items array
	Count *int64                      `json:"count,omitempty"`
	Items []components.SearchSettings `json:"items,omitempty"`
}

func (o *GetSystemSettingsSearchLimitsResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetSystemSettingsSearchLimitsResponseBody) GetItems() []components.SearchSettings {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetSystemSettingsSearchLimitsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of SearchSettings objects
	Object *GetSystemSettingsSearchLimitsResponseBody
}

func (o *GetSystemSettingsSearchLimitsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSystemSettingsSearchLimitsResponse) GetObject() *GetSystemSettingsSearchLimitsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
