// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetSystemDistributedUpgradeDownloadByFileRequest struct {
	// Name of the file to be downloaded
	File string `pathParam:"style=simple,explode=false,name=file"`
}

func (o *GetSystemDistributedUpgradeDownloadByFileRequest) GetFile() string {
	if o == nil {
		return ""
	}
	return o.File
}

// GetSystemDistributedUpgradeDownloadByFileResponseBody - a list of any objects
type GetSystemDistributedUpgradeDownloadByFileResponseBody struct {
	// number of items present in the items array
	Count *int64           `json:"count,omitempty"`
	Items []map[string]any `json:"items,omitempty"`
}

func (o *GetSystemDistributedUpgradeDownloadByFileResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetSystemDistributedUpgradeDownloadByFileResponseBody) GetItems() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetSystemDistributedUpgradeDownloadByFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of any objects
	Object *GetSystemDistributedUpgradeDownloadByFileResponseBody
}

func (o *GetSystemDistributedUpgradeDownloadByFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSystemDistributedUpgradeDownloadByFileResponse) GetObject() *GetSystemDistributedUpgradeDownloadByFileResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
