// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetSearchDashboardACLByIDRequest struct {
	// Unique ID for ACL Get
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetSearchDashboardACLByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetSearchDashboardACLByIDResponseBody - a list of UserAccessControlList objects
type GetSearchDashboardACLByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                             `json:"count,omitempty"`
	Items []components.UserAccessControlList `json:"items,omitempty"`
}

func (o *GetSearchDashboardACLByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetSearchDashboardACLByIDResponseBody) GetItems() []components.UserAccessControlList {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetSearchDashboardACLByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of UserAccessControlList objects
	Object *GetSearchDashboardACLByIDResponseBody
}

func (o *GetSearchDashboardACLByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSearchDashboardACLByIDResponse) GetObject() *GetSearchDashboardACLByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
