// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// GetSystemProcessesResponseBody - a list of ProcessEntry objects
type GetSystemProcessesResponseBody struct {
	// number of items present in the items array
	Count *int64                    `json:"count,omitempty"`
	Items []components.ProcessEntry `json:"items,omitempty"`
}

func (o *GetSystemProcessesResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetSystemProcessesResponseBody) GetItems() []components.ProcessEntry {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetSystemProcessesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of ProcessEntry objects
	Object *GetSystemProcessesResponseBody
}

func (o *GetSystemProcessesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSystemProcessesResponse) GetObject() *GetSystemProcessesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
