// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// ListAppscopeLibEntryResponseBody - a list of AppscopeLibEntry objects
type ListAppscopeLibEntryResponseBody struct {
	// number of items present in the items array
	Count *int64                        `json:"count,omitempty"`
	Items []components.AppscopeLibEntry `json:"items,omitempty"`
}

func (o *ListAppscopeLibEntryResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ListAppscopeLibEntryResponseBody) GetItems() []components.AppscopeLibEntry {
	if o == nil {
		return nil
	}
	return o.Items
}

type ListAppscopeLibEntryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of AppscopeLibEntry objects
	Object *ListAppscopeLibEntryResponseBody
}

func (o *ListAppscopeLibEntryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListAppscopeLibEntryResponse) GetObject() *ListAppscopeLibEntryResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
