// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// ListDatasetProviderResponseBody - a list of DatasetProvider objects
type ListDatasetProviderResponseBody struct {
	// number of items present in the items array
	Count *int64 `json:"count,omitempty"`
	Items []any  `json:"items,omitempty"`
}

func (o *ListDatasetProviderResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ListDatasetProviderResponseBody) GetItems() []any {
	if o == nil {
		return nil
	}
	return o.Items
}

type ListDatasetProviderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of DatasetProvider objects
	Object *ListDatasetProviderResponseBody
}

func (o *ListDatasetProviderResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListDatasetProviderResponse) GetObject() *ListDatasetProviderResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
