// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// ListSearchJobResponseBody - a list of SearchJob objects
type ListSearchJobResponseBody struct {
	// number of items present in the items array
	Count *int64                 `json:"count,omitempty"`
	Items []components.SearchJob `json:"items,omitempty"`
}

func (o *ListSearchJobResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ListSearchJobResponseBody) GetItems() []components.SearchJob {
	if o == nil {
		return nil
	}
	return o.Items
}

type ListSearchJobResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of SearchJob objects
	Object *ListSearchJobResponseBody
}

func (o *ListSearchJobResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListSearchJobResponse) GetObject() *ListSearchJobResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
