// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// ListConditionResponseBody - a list of Condition objects
type ListConditionResponseBody struct {
	// number of items present in the items array
	Count *int64                 `json:"count,omitempty"`
	Items []components.Condition `json:"items,omitempty"`
}

func (o *ListConditionResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ListConditionResponseBody) GetItems() []components.Condition {
	if o == nil {
		return nil
	}
	return o.Items
}

type ListConditionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Condition objects
	Object *ListConditionResponseBody
}

func (o *ListConditionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListConditionResponse) GetObject() *ListConditionResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
