// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// ListRegexLibEntryResponseBody - a list of RegexLibEntry objects
type ListRegexLibEntryResponseBody struct {
	// number of items present in the items array
	Count *int64                     `json:"count,omitempty"`
	Items []components.RegexLibEntry `json:"items,omitempty"`
}

func (o *ListRegexLibEntryResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ListRegexLibEntryResponseBody) GetItems() []components.RegexLibEntry {
	if o == nil {
		return nil
	}
	return o.Items
}

type ListRegexLibEntryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of RegexLibEntry objects
	Object *ListRegexLibEntryResponseBody
}

func (o *ListRegexLibEntryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListRegexLibEntryResponse) GetObject() *ListRegexLibEntryResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
