// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// ListLoggerConfigResponseBody - a list of LoggerConfig objects
type ListLoggerConfigResponseBody struct {
	// number of items present in the items array
	Count *int64                    `json:"count,omitempty"`
	Items []components.LoggerConfig `json:"items,omitempty"`
}

func (o *ListLoggerConfigResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ListLoggerConfigResponseBody) GetItems() []components.LoggerConfig {
	if o == nil {
		return nil
	}
	return o.Items
}

type ListLoggerConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of LoggerConfig objects
	Object *ListLoggerConfigResponseBody
}

func (o *ListLoggerConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListLoggerConfigResponse) GetObject() *ListLoggerConfigResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
