// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateSubscriptionByIDRequest struct {
	// Subscription ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *UpdateSubscriptionByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// UpdateSubscriptionByIDResponseBody - a list of Subscription objects
type UpdateSubscriptionByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                    `json:"count,omitempty"`
	Items []components.Subscription `json:"items,omitempty"`
}

func (o *UpdateSubscriptionByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *UpdateSubscriptionByIDResponseBody) GetItems() []components.Subscription {
	if o == nil {
		return nil
	}
	return o.Items
}

type UpdateSubscriptionByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Subscription objects
	Object *UpdateSubscriptionByIDResponseBody
}

func (o *UpdateSubscriptionByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateSubscriptionByIDResponse) GetObject() *UpdateSubscriptionByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
