// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateLibSchemasByIDRequest struct {
	// Unique ID to PATCH
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Schema object to be updated
	SchemaLibEntry components.SchemaLibEntry `request:"mediaType=application/json"`
}

func (o *UpdateLibSchemasByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateLibSchemasByIDRequest) GetSchemaLibEntry() components.SchemaLibEntry {
	if o == nil {
		return components.SchemaLibEntry{}
	}
	return o.SchemaLibEntry
}

// UpdateLibSchemasByIDResponseBody - a list of Schema objects
type UpdateLibSchemasByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                      `json:"count,omitempty"`
	Items []components.SchemaLibEntry `json:"items,omitempty"`
}

func (o *UpdateLibSchemasByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *UpdateLibSchemasByIDResponseBody) GetItems() []components.SchemaLibEntry {
	if o == nil {
		return nil
	}
	return o.Items
}

type UpdateLibSchemasByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Schema objects
	Object *UpdateLibSchemasByIDResponseBody
}

func (o *UpdateLibSchemasByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateLibSchemasByIDResponse) GetObject() *UpdateLibSchemasByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
