// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateDataSampleByIDRequest struct {
	// Unique ID to PATCH
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// DataSample object to be updated
	DataSample components.DataSample `request:"mediaType=application/json"`
}

func (o *UpdateDataSampleByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateDataSampleByIDRequest) GetDataSample() components.DataSample {
	if o == nil {
		return components.DataSample{}
	}
	return o.DataSample
}

// UpdateDataSampleByIDResponseBody - a list of DataSample objects
type UpdateDataSampleByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                  `json:"count,omitempty"`
	Items []components.DataSample `json:"items,omitempty"`
}

func (o *UpdateDataSampleByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *UpdateDataSampleByIDResponseBody) GetItems() []components.DataSample {
	if o == nil {
		return nil
	}
	return o.Items
}

type UpdateDataSampleByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of DataSample objects
	Object *UpdateDataSampleByIDResponseBody
}

func (o *UpdateDataSampleByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateDataSampleByIDResponse) GetObject() *UpdateDataSampleByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
