// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateSearchMacroByIDRequest struct {
	// Unique ID to PATCH
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// SearchMacro object to be updated
	SearchMacro components.SearchMacro `request:"mediaType=application/json"`
}

func (o *UpdateSearchMacroByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateSearchMacroByIDRequest) GetSearchMacro() components.SearchMacro {
	if o == nil {
		return components.SearchMacro{}
	}
	return o.SearchMacro
}

// UpdateSearchMacroByIDResponseBody - a list of SearchMacro objects
type UpdateSearchMacroByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                   `json:"count,omitempty"`
	Items []components.SearchMacro `json:"items,omitempty"`
}

func (o *UpdateSearchMacroByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *UpdateSearchMacroByIDResponseBody) GetItems() []components.SearchMacro {
	if o == nil {
		return nil
	}
	return o.Items
}

type UpdateSearchMacroByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of SearchMacro objects
	Object *UpdateSearchMacroByIDResponseBody
}

func (o *UpdateSearchMacroByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateSearchMacroByIDResponse) GetObject() *UpdateSearchMacroByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
