// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdatePolicyRuleByIDRequest struct {
	// Unique ID to PATCH
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// PolicyRule object to be updated
	PolicyRule components.PolicyRule `request:"mediaType=application/json"`
}

func (o *UpdatePolicyRuleByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdatePolicyRuleByIDRequest) GetPolicyRule() components.PolicyRule {
	if o == nil {
		return components.PolicyRule{}
	}
	return o.PolicyRule
}

// UpdatePolicyRuleByIDResponseBody - a list of PolicyRule objects
type UpdatePolicyRuleByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                  `json:"count,omitempty"`
	Items []components.PolicyRule `json:"items,omitempty"`
}

func (o *UpdatePolicyRuleByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *UpdatePolicyRuleByIDResponseBody) GetItems() []components.PolicyRule {
	if o == nil {
		return nil
	}
	return o.Items
}

type UpdatePolicyRuleByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of PolicyRule objects
	Object *UpdatePolicyRuleByIDResponseBody
}

func (o *UpdatePolicyRuleByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdatePolicyRuleByIDResponse) GetObject() *UpdatePolicyRuleByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
