"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class DatasetOrigin(str, Enum):
    LEADER_LOCAL = "leader_local"
    REMOTE = "remote"
    WORKER_LOCAL = "worker_local"
