"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .globalvar import GlobalVar, GlobalVarTypedDict
from cribl.types import BaseModel
from cribl.utils import FieldMetadata, PathParamMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetGlobalVariableByIDRequestTypedDict(TypedDict):
    id: str
    r"""Unique ID to GET"""


class GetGlobalVariableByIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique ID to GET"""


class GetGlobalVariableByIDResponseBodyTypedDict(TypedDict):
    r"""a list of Global Variable objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[GlobalVarTypedDict]]


class GetGlobalVariableByIDResponseBody(BaseModel):
    r"""a list of Global Variable objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[GlobalVar]] = None
