"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Union
from typing_extensions import TypeAliasType


SearchParameterValueTypedDict = TypeAliasType(
    "SearchParameterValueTypedDict", Union[str, float, bool]
)


SearchParameterValue = TypeAliasType("SearchParameterValue", Union[str, float, bool])
