"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .databaseconnectionconfig import (
    DatabaseConnectionConfig,
    DatabaseConnectionConfigTypedDict,
)
from cribl.types import BaseModel
from cribl.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateDatabaseConnectionConfigByIDRequestTypedDict(TypedDict):
    id_param: str
    r"""Unique ID to PATCH"""
    database_connection_config: DatabaseConnectionConfigTypedDict
    r"""DatabaseConnectionConfig object to be updated"""


class UpdateDatabaseConnectionConfigByIDRequest(BaseModel):
    id_param: Annotated[
        str,
        pydantic.Field(alias="id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique ID to PATCH"""

    database_connection_config: Annotated[
        DatabaseConnectionConfig,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""DatabaseConnectionConfig object to be updated"""


class UpdateDatabaseConnectionConfigByIDResponseBodyTypedDict(TypedDict):
    r"""a list of DatabaseConnectionConfig objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[DatabaseConnectionConfigTypedDict]]


class UpdateDatabaseConnectionConfigByIDResponseBody(BaseModel):
    r"""a list of DatabaseConnectionConfig objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[DatabaseConnectionConfig]] = None
