"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl.types import BaseModel
from cribl.utils import FieldMetadata, QueryParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateLookupFileRequestTypedDict(TypedDict):
    request_body: str
    r"""CSV text"""
    filename: NotRequired[str]
    r"""query LookupFilenameSchema required Filename"""


class UpdateLookupFileRequest(BaseModel):
    request_body: Annotated[
        str, FieldMetadata(request=RequestMetadata(media_type="text/csv"))
    ]
    r"""CSV text"""

    filename: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""query LookupFilenameSchema required Filename"""
